"""Attachment storage.

Files are addressed by an opaque ``storage_key``, never by a URL or a filesystem
path. That indirection is the whole point: moving from local disk to object
storage becomes a new implementation of this interface, with no migration and no
change to any stored row.
"""

from __future__ import annotations

import secrets
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path

from app.core.config import settings
from app.core.exceptions import PayloadTooLargeError, UnsupportedMediaTypeError
from app.core.logging import get_logger

logger = get_logger(__name__)


class StorageBackend(ABC):
    """What any storage implementation must provide."""

    @abstractmethod
    async def save(self, data: bytes, *, filename: str, content_type: str) -> str:
        """Persist bytes and return the key that addresses them."""

    @abstractmethod
    async def delete(self, storage_key: str) -> None: ...

    @abstractmethod
    def url_for(self, storage_key: str) -> str:
        """Return a URL a browser can fetch."""

    @abstractmethod
    def path_for(self, storage_key: str) -> Path | None:
        """Local path, where one exists. None for remote backends."""


class LocalDiskStorage(StorageBackend):
    """Files on the local filesystem, served back through the API.

    Correct for a single-instance deployment with a mounted volume, which is what
    this project deploys to. S3 or similar would be the substitution for anything
    horizontally scaled.
    """

    def __init__(self, root: Path | None = None) -> None:
        self.root = root or settings.upload_dir
        self.root.mkdir(parents=True, exist_ok=True)

    async def save(self, data: bytes, *, filename: str, content_type: str) -> str:
        if len(data) > settings.max_upload_bytes:
            raise PayloadTooLargeError(
                f"Files must be under {settings.max_upload_bytes // (1024 * 1024)} MB."
            )
        if content_type not in settings.allowed_upload_types:
            raise UnsupportedMediaTypeError(f"{content_type} files are not supported.")

        # The stored name is generated, never taken from the upload. A filename is
        # attacker-controlled: honouring it invites path traversal ('../../etc/...')
        # and lets one upload overwrite another. The original is kept in the
        # database column for display only.
        suffix = Path(filename).suffix.lower()[:10]
        today = datetime.now().strftime("%Y/%m/%d")
        key = f"{today}/{secrets.token_urlsafe(16)}{suffix}"

        destination = self.root / key
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        logger.info("attachment_stored", extra={"storage_key": key, "bytes": len(data)})
        return key

    async def delete(self, storage_key: str) -> None:
        target = self._safe_path(storage_key)
        if target and target.exists():
            target.unlink()

    def url_for(self, storage_key: str) -> str:
        return f"{settings.public_base_url}{settings.api_v1_prefix}/attachments/{storage_key}"

    def path_for(self, storage_key: str) -> Path | None:
        return self._safe_path(storage_key)

    def _safe_path(self, storage_key: str) -> Path | None:
        """Resolve a key to a path, refusing anything that escapes the root.

        Keys are generated by this class, but they also arrive from URLs, so this
        is checked rather than assumed — a traversal here would expose the whole
        filesystem.
        """
        candidate = (self.root / storage_key).resolve()
        root = self.root.resolve()
        if root not in candidate.parents and candidate != root:
            logger.warning("attachment_path_escape_blocked", extra={"storage_key": storage_key})
            return None
        return candidate


storage: StorageBackend = LocalDiskStorage()
