"""create core messaging schema

Revision ID: 698f2d6a6f8c
Revises: 
Created: 2026-07-26 11:47:27.056883+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '698f2d6a6f8c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('avatar_color', sa.String(length=16), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_is_online', ['is_online'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('contacts',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('contact_user_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name=op.f('fk_contacts_contact_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_contacts_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('owner_id', 'contact_user_id', name='uq_contact_owner_target')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_contact_user_id'), ['contact_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_owner_id'), ['owner_id'], unique=False)

    op.create_table('conversations',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('direct_key', sa.String(length=80), nullable=True),
    sa.Column('disappearing_seconds', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('direct', 'group')", name=op.f('ck_conversations_conversation_type_valid')),
    sa.CheckConstraint('disappearing_seconds >= 0', name=op.f('ck_conversations_disappearing_seconds_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('direct_key', name=op.f('uq_conversations_direct_key'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_last_message_at', ['last_message_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('verification_codes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_codes'))
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index('ix_verification_codes_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('encryption_key_id', sa.String(length=64), nullable=True),
    sa.Column('encryption_algorithm', sa.String(length=32), nullable=True),
    sa.Column('system_event', sa.String(length=48), nullable=True),
    sa.Column('system_meta', sa.JSON(), nullable=True),
    sa.Column('reply_to_message_id', sa.String(), nullable=True),
    sa.Column('client_message_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('text', 'media', 'system')", name=op.f('ck_messages_message_type_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], name=op.f('fk_messages_reply_to_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('sender_id', 'client_message_id', name='uq_message_sender_client_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('attachments',
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_attachments_attachment_size_non_negative')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_message_id', sa.String(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('member', 'admin')", name=op.f('ck_conversation_participants_participant_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], name=op.f('fk_conversation_participants_last_read_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_participants')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_participant_conversation_user')
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_participants_user_conversation', ['user_id', 'conversation_id'], unique=False)

    op.create_table('message_reactions',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_reactions_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_reactions')),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_reaction_message_user_emoji')
    )
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('message_receipts',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_receipts_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_receipts')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_receipt_message_user')
    )
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_receipts_user_read', ['user_id', 'read_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_receipts_user_read')
        batch_op.drop_index(batch_op.f('ix_message_receipts_message_id'))

    op.drop_table('message_receipts')
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))

    op.drop_table('message_reactions')
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_participants_user_conversation')
        batch_op.drop_index(batch_op.f('ix_conversation_participants_conversation_id'))

    op.drop_table('conversation_participants')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_message_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_expires_at'))
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_codes_user_created')

    op.drop_table('verification_codes')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_last_message_at')

    op.drop_table('conversations')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_contact_user_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index('ix_users_is_online')

    op.drop_table('users')
    # ### end Alembic commands ###
